<h1> Start of Day 2

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
arr = np.arange(5)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [6]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [7]:
arr.resize(2,3)

In [8]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr2 = np.arange(5)

In [10]:
arr2

array([0, 1, 2, 3, 4])

In [20]:
arr = arr.reshape(2,3)

In [21]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

<h3> Vectorization

In [22]:
arr = np.arange(10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
newList = []
for i in arr:
    newList.append(i+10)

In [25]:
newArr = np.array(newList)

In [26]:
newArr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
newArr = newArr + 10

newArr

In [31]:
ages = np.array([19,35,18,42,17,40])
arrb = ages<20

In [32]:
ages[arrb]

array([19, 18, 17])

In [33]:
arrb2 = (ages<20) | (ages>40) 

In [34]:
ages[arrb2]

array([19, 18, 42, 17])

In [35]:
ages[(ages>20)&(ages<40)]

array([35])

In [50]:
sal = np.array([20000,30000,25000,22000,260000])

In [37]:
salAvg = sum(sal)/len(sal)

In [38]:
salAvg

24600.0

In [39]:
salAvg = sal.mean()

In [40]:
salAvg

24600.0

In [41]:
sal.sort()

In [42]:
sal

array([20000, 22000, 25000, 26000, 30000])

In [43]:
print(sal[len(sal)/2])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [51]:
print(sal[round(len(sal)/2)])

25000


In [53]:
np.median(sal)

25000.0

In [54]:
sal**2

array([  400000000,   900000000,   625000000,   484000000, 67600000000])

In [56]:
np.round(np.mean(sal**2),2)

14001800000.0

In [57]:
np.var(sal)

8903840000.0

In [58]:
np.sqrt(np.var(sal))

94360.1610850681

In [59]:
np.std(sal)

94360.1610850681

In [60]:
np.round(np.std(sal))

94360.0

In [61]:
np.quantile(sal,q=.8) #80th percentile

76000.00000000004

<h2>End of day 2