In [1]:
import numpy as np

In [2]:
arr = np.array([45,43,35,37,39,43,46,48,37,38])

In [3]:
avgTemp = np.mean(arr)
avgTemp

41.1

In [4]:
medianTemp = np.median(arr)
medianTemp

41.0

In [13]:
arr2 =np.random.rand(3,2)

In [14]:
arr2

array([[0.89903823, 0.27874169],
       [0.3705261 , 0.44721772],
       [0.7665681 , 0.04438904]])

In [15]:
np.random.seed(40)
arr3 = np.random.rand(3,2)

In [17]:
arr3

array([[0.40768703, 0.05536604],
       [0.78853488, 0.28730518],
       [0.45035059, 0.30391231]])

In [18]:
newArr = np.random.normal(loc=45,scale=1,size=10)

In [19]:
newArr

array([47.29249034, 45.48881005, 45.71026699, 46.05553444, 45.0540731 ,
       45.25795342, 45.58828165, 45.88524424, 43.98299298, 44.86630697])

In [20]:
newArr2 = np.random.rand(5)

In [21]:
newArr2

array([0.83530018, 0.20224823, 0.17420267, 0.44914708, 0.66979478])

In [22]:
newArr3 = np.random.randint(low=10,high=50,size=10)

In [23]:
newArr3

array([25, 13, 40, 33, 45, 44, 41, 28, 15, 26])

In [25]:
v1 = np.array([10,10,10])
v2 = np.array([5,5,5])

In [26]:
np.dot(v1,v2)

150

In [29]:
randomArray1 = np.random.randint(2,7,(2,4))
randomArray2 = np.random.randint(2,7,(4,2))

In [30]:
np.dot(randomArray1,randomArray2)

array([[46, 66],
       [51, 68]])

In [31]:
ara = np.zeros((3,2),dtype='int')

In [32]:
ara

array([[0, 0],
       [0, 0],
       [0, 0]])

In [33]:
ara2 = np.identity(4,dtype='int')
ara2

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [34]:
ages = np.array([19,35,18,42,17,40])

In [42]:
newAges = np.where(ages<20,'T','NT')

In [43]:
newAges

array(['T', 'NT', 'T', 'NT', 'T', 'NT'], dtype='<U2')